server:
  port: 8081
  context-path: /curd
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    date-format: yyyy-MM-dd

  messages:
    basename: i18n.login

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  datasource:
    # useUnicode=true&characterEncoding=utf-8 结果保存到数据库变为 ? 的问题
    url: jdbc:mysql://localhost:3306/empsys?serverTimezone=UTC&ENGINE=InnoDB&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    type: org.springframework.jdbc.datasource.DelegatingDataSource

